project_id = "gnyflfsjaqnxgnpsshwe"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[functions.create-user]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.send-permission-notification]
verify_jwt = false

[functions.collaborative-editing]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-company-user]
verify_jwt = true

[functions.fetch-weather]
verify_jwt = true