// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnyflfsjaqnxgnpsshwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdueWZsZnNqYXFueGducHNzaHdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MjI1NjksImV4cCI6MjA2NzQ5ODU2OX0.IpmWKi4bR2Ybf2MvqEjjb0B223t1rTQ2MZT9OA1wuoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});